package com.zkingsoft.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.matrix.core.pojo.PaginationVO;
import com.zkingsoft.bean.WebArticle;


/**
 * This field was generated by Zking.software.Codegen.
 * @date 2016-12-01 10:36
 */


public interface WebArticleDao{

	public int insert(WebArticle webArticle);
   	
   	public int batchInsert(@Param("list") List<WebArticle> webArticleList);
   	
	public int updateByMap(Map<String, Object> modifyMap);
	
	public int updateByModel(WebArticle webArticle);
	
	public int deleteByIds(@Param("list") List<String> list);
	
	public int deleteById(String artId);

	public int deleteByModel(@Param("record") WebArticle webArticle);
	
	public List<WebArticle> selectInPage(@Param("record") WebArticle webArticle, @Param("pageVo") PaginationVO pageVo);

	public List<WebArticle> selectByModel(@Param("record") WebArticle webArticle);
	
	public int  selectTotalRecord(@Param("record") WebArticle webArticle);
	
	public WebArticle  selectById(String artId);
	
	public WebArticle  selectForUpdate(String artId);

	public WebArticle selectAround(@Param("artId")String artId,@Param("around") int i);

	public List<WebArticle> selectByWord(@Param("searchWord")String searchWord);
	
}